name: calisma
channels:
  - defaults
  - conda-forge
# To update this regularly, or find a way to automaticall update as soon as a package is installed.
dependencies:
  - python=3.11.5
  - pandas=2.2.2
  - matplotlib=3.9.2
  - jupyter
  - cartopy=0.22.0
  - scipy
  - statsmodels
  - scikit-learn=1.5.1
  - seaborn=0.13.2
  - netcdf4=1.6.2
  - metpy=1.4.0  # Ensure compatibility with MetPy
  - metvars  # No specific version; ensure it's installable
  - dask-ml=2023.1.1  # Version with StandardScaler and train_test_split
  - xgboost=1.7.6  # Latest version for compatibility
  - scikit-learn=1.3.0  # Ensure compatibility with r2_score and mean_squared_error
  - shap=0.42.1  # Specify version to ensure compatibility
  - jsonschema  # Included as it's common for JSON operations
  - cloudpickle  # For pickle support, often needed for Dask
  - pip:
    - metvars
    - metpy